name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Build
        run:  npm install && npm run build -- --base /apps
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-apps-dist
          path: dist
